services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: totvs@123
      MYSQL_DATABASE: pontos_turisticos
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
