services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=totvs@123
      - DB_NAME=pontos_turisticos
      - DB_PORT=3306
      - PORT=3000
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: totvs@123
      MYSQL_DATABASE: pontos_turisticos
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
